# Release-plz configuration
# Documentation: https://release-plz.dev/docs/config

[workspace]
# Enable changelog generation using git-cliff
changelog_update = true

# Customize git-cliff changelog configuration
changelog_config = "cliff.toml"

# Dependencies update configuration
dependencies_update = true

# Allow dirty working tree (useful for CI)
allow_dirty = false

# Git configuration
git_tag_enable = true
# NO 'v' prefix - project convention
git_tag_name = "{{ version }}"

# Git release configuration
git_release_enable = true
git_release_draft = false

# PR configuration
pr_name = "chore: release {{ version }}"

# Semver check configuration (requires cargo-semver-checks)
semver_check = true

# Use conventional commits to determine version bumps
# - feat: minor version bump
# - fix: patch version bump  
# - feat!: or BREAKING CHANGE: major version bump

# Package-specific configuration - don't publish to crates.io
[[package]]
name = "cuenv"
# Don't publish to crates.io - project uses GitHub releases only
publish = false

# Don't publish internal workspace crates to crates.io
[[package]]
name = "cuenv-core"
publish = false
release = false

[[package]]
name = "cuenv-libcue-ffi-bridge"
publish = false
release = false

[[package]]
name = "cuenv-config"
publish = false
release = false

[[package]]
name = "cuenv-env"
publish = false
release = false

[[package]]
name = "cuenv-shell"
publish = false
release = false

[[package]]
name = "cuenv-task"
publish = false
release = false

[[package]]
name = "cuenv-cache"
publish = false
release = false

[[package]]
name = "cuenv-security"
publish = false
release = false

[[package]]
name = "cuenv-tui"
publish = false
release = false

[[package]]
name = "cuenv-hooks"
publish = false
release = false

[[package]]
name = "cuenv-utils"
publish = false
release = false
