# Release-plz configuration
# Documentation: https://release-plz.dev/docs/config

[workspace]
# Enable shared versioning across all workspace crates
# All crates will use the same version number from workspace.package.version
shared_version = true

# Enable changelog generation using git-cliff
changelog_update = true

# Customize git-cliff changelog configuration
changelog_config = "cliff.toml"

# Dependencies update configuration
dependencies_update = true

# Allow dirty working tree (useful for CI)
allow_dirty = false

# Git configuration
git_tag_enable = true
# NO 'v' prefix - project convention
git_tag_name = "{{ version }}"

# Git release configuration
git_release_enable = true
git_release_draft = false

# PR configuration
pr_name = "chore: release {{ version }}"

# Semver check configuration (requires cargo-semver-checks)
semver_check = true

# Use conventional commits to determine version bumps
# - feat: minor version bump
# - fix: patch version bump  
# - feat!: or BREAKING CHANGE: major version bump
# 
# Changelog groups commits by type
changelog_include = [
  "feat",
  "fix",
  "perf",
  "refactor",
  "build",
  "chore",
  "docs",
  "style",
  "test",
]

# Package-specific configuration - only publish the main CLI crate
[[package]]
name = "cuenv"
# This is the main binary - publish to crates.io
publish = true

# Don't publish internal workspace crates to crates.io
[[package]]
name = "cuenv-core"
publish = false

[[package]]
name = "cuenv-libcue-ffi-bridge"
publish = false

[[package]]
name = "cuenv-config"
publish = false

[[package]]
name = "cuenv-env"
publish = false

[[package]]
name = "cuenv-shell"
publish = false

[[package]]
name = "cuenv-task"
publish = false

[[package]]
name = "cuenv-cache"
publish = false

[[package]]
name = "cuenv-security"
publish = false

[[package]]
name = "cuenv-tui"
publish = false

[[package]]
name = "cuenv-hooks"
publish = false

[[package]]
name = "cuenv-utils"
publish = false
