# Nextest configuration for cuenv tests

[profile.default]
# Set reasonable defaults for all tests
slow-timeout = { period = "10s", terminate-after = 3 }
test-threads = "num-cpus"

# Process group cleanup test needs serial execution
[[profile.default.overrides]]
filter = "test(process_group_cleanup)"
threads-required = 1
slow-timeout = { period = "30s" }

# Cache and concurrent tests need limited parallelism
[[profile.default.overrides]]
filter = "test(concurrent) | test(cache)"
slow-timeout = { period = "20s" }

# Chaos engineering tests need more time but not infinite
[[profile.default.overrides]]
filter = "test(test_memory_pressure_chaos) | test(test_multi_vector_chaos)"
threads-required = 1
slow-timeout = { period = "60s", terminate-after = 2 }

# For CI runs, be more conservative to avoid TLS exhaustion
[profile.ci]
test-threads = 1
slow-timeout = { period = "60s", terminate-after = 2 }
fail-fast = false

# Ignore highly concurrent tests in CI to avoid TLS exhaustion
# Note: nextest 0.9.x doesn't support status = "skip", so we handle this with filtering instead

# Run integration tests serially in CI
[[profile.ci.overrides]]
filter = "test(integration) | test(comprehensive)"
threads-required = 1
slow-timeout = { period = "120s", terminate-after = 1 }

# Environment override test has race condition with concurrent execution
[[profile.ci.overrides]]
filter = "test(test_environment_overrides)"
threads-required = 1
slow-timeout = { period = "60s", terminate-after = 1 }

# Quick profile for development
[profile.quick]
test-threads = "num-cpus"
retries = 0
fail-fast = true
