name: ci
# CI workflow for cuenv - optimized with comprehensive caching
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
  CUENV_ENV: ci
permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v4
      - name: cache-cargo-target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.rust }}-cargo-
            ${{ runner.os }}-cargo-
      - name: nix-install
        if: runner.os != 'Windows'
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: magic-nix-cache
        if: runner.os != 'Windows'
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: cache-nix-store
        if: runner.os != 'Windows'
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          gc-max-store-size-macos: 1073741824
      - name: nix-cache
        if: runner.os != 'Windows'
        uses: cachix/cachix-action@v15
        with:
          name: cuenv
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: ${{ matrix.rust != 'stable' }}
      # Windows-specific setup
      - name: setup-rust-windows
        if: runner.os == 'Windows'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - name: setup-go-windows
        if: runner.os == 'Windows'
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      # Build once - Nix will cache this (Unix only)
      - name: nix-build
        if: runner.os != 'Windows'
        run: nix build .#cuenv --print-build-logs
      # Run flake checks - uses cached build from above (Unix only)
      - name: nix-flake-checks
        if: runner.os != 'Windows'
        run: nix flake check --print-build-logs -L
      # Windows build
      - name: windows-build
        if: runner.os == 'Windows'
        run: |
          # Set up Go vendor for Windows
          cd crates/libcue-ffi-bridge
          go mod vendor
          cd ../..
          # Build with cargo
          cargo build --release
      # Run tests using cached Nix environment (Unix only)
      - name: cuenv-test-all
        if: runner.os != 'Windows'
        run: |
          # Use cached dependencies but run tests directly for cross-platform compatibility
          nix develop --command cargo nextest run --profile ci --no-fail-fast
      # Run tests on Windows
      - name: cuenv-test-all-windows
        if: runner.os == 'Windows'
        run: |
          # Install nextest for Windows
          cargo install cargo-nextest --locked
          # Run tests
          cargo nextest run --profile ci --no-fail-fast
      - name: cuenv-test-examples
        if: runner.os != 'Windows'
        run: |
          # Use the binary from Nix build (already cached)
          mkdir -p target/debug
          cp result/bin/cuenv target/debug/

          # To ensure we test the local CUE schema, not a remote one,
          # we manually populate the CUE module cache. This avoids
          # running `cue mod get`.
          # CUE's cache path is cue/cue.mod/pkg/
          export CUE_CACHE_DIR="examples/cue.mod/pkg"
          export SCHEMA_PATH="$CUE_CACHE_DIR/github.com/rawkode/cuenv@v0"
          mkdir -p "$SCHEMA_PATH"
          cp -r cue/* "$SCHEMA_PATH/"

          # Run the example tests
          ./scripts/test-examples.sh
  test-beta:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [beta]
    steps:
      - uses: actions/checkout@v4
      - name: cache-cargo-target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.rust }}-cargo-
            ${{ runner.os }}-cargo-
      - name: nix-install
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: magic-nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: cache-nix-store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          gc-max-store-size-macos: 1073741824
      - name: nix-cache
        uses: cachix/cachix-action@v15
        with:
          name: cuenv
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: ${{ matrix.rust != 'stable' }}
      # Build once - Nix will cache this
      - name: nix-build
        run: nix build .#cuenv --print-build-logs
      # Run flake checks - uses cached build from above
      - name: nix-flake-checks
        run: nix flake check --print-build-logs -L
      # Run tests using cached Nix environment
      - name: cuenv-test-all
        run: |
          # Use cached dependencies but run tests directly for cross-platform compatibility
          nix develop --command cargo nextest run --profile ci --no-fail-fast
  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    if: always() && (needs.test.result == 'success')
    steps:
      - uses: actions/checkout@v4
      - name: cache-cargo-target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ubuntu-latest-stable-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-latest-stable-cargo-
            ubuntu-latest-cargo-
      - name: nix-install
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: magic-nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: cache-nix-store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-ubuntu-latest-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-ubuntu-latest-
          gc-max-store-size-linux: 1073741824
      - name: nix-cache
        uses: cachix/cachix-action@v15
        with:
          name: cuenv
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: false
      - name: generate-coverage
        run: |
          # Use Nix cache - build will be instant if already cached
          nix build .#cuenv
          # Generate coverage report using cached dependencies
          nix develop --command cargo llvm-cov nextest --lcov --output-path lcov.info
      - name: upload-coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./lcov.info
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
