name: deploy
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  website:
    runs-on: ubuntu-latest
    needs: crates-io
    steps:
      - name: git-checkout
        uses: actions/checkout@v4
      - name: bun-setup
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: dependencies-install
        run: bun install
        working-directory: ./website
      - name: website-build
        run: bun run build
        working-directory: ./website
        env:
          CI: "true"
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: cloudflare-deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./website
