name: Example with cuenv
on:
  workflow_dispatch:
  pull_request:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup cuenv
        uses: rawkode/cuenv/github/action/setup-cuenv@main
        with:
          version: '0.3.1'
      - name: Load environment
        run: |
          # cuenv will read env.cue and set environment variables
          eval "$(cuenv load)"

          # Now all variables from env.cue are available
          echo "CARGO_TERM_COLOR=$CARGO_TERM_COLOR"
          echo "RUST_BACKTRACE=$RUST_BACKTRACE"
          echo "CUENV_ENV=$CUENV_ENV"
      - name: Run cuenv tasks
        run: |
          # List available tasks
          cuenv run

          # Run a specific task (if defined in env.cue)
          cuenv run build
      - name: Use cuenv in scripts
        run: |-
          # You can also use cuenv exec to run commands with the environment
          cuenv exec cargo --version
          cuenv exec echo "Running with cuenv environment"
