name: Test Setup Action (Disabled until proper releases)
# Temporarily disabled - setup-cuenv action requires proper releases with musl/darwin assets
# Current 0.3.9 release only has gnu assets, causing downloads to fail  
# Will re-enable once release pipeline produces correct assets
on:
  workflow_dispatch: # Manual trigger only
    inputs:
      force_run:
        description: 'Force run (only use if releases are working)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'
jobs:
  test-latest:
    runs-on: ${{ matrix.os }}
    if: inputs.force_run == 'true'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup cuenv (latest)
        uses: ./github/action/setup-cuenv
        id: setup
      - name: Verify installation
        run: |
          cuenv --version
          echo "Installed version: ${{ steps.setup.outputs.version }}"
          echo "Installed at: ${{ steps.setup.outputs.path }}"
      - name: Test cuenv functionality
        run: |
          cuenv export
          cuenv run -- echo "Successfully ran command with cuenv!"
  test-specific-version:
    runs-on: ubuntu-latest
    if: inputs.force_run == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup cuenv (specific version)
        uses: ./github/action/setup-cuenv
        with:
          version: 0.2.7
      - name: Verify version
        run: |
          cuenv --version | grep -q "0.2.7" || (echo "Version mismatch!" && exit 1)
  test-custom-directory:
    runs-on: ubuntu-latest
    if: inputs.force_run == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup cuenv (custom directory)
        uses: ./github/action/setup-cuenv
        with:
          install-dir: /tmp/custom-bin
      - name: Verify installation location
        run: |-
          test -f /tmp/custom-bin/cuenv || (echo "cuenv not found in custom directory!" && exit 1)
          /tmp/custom-bin/cuenv --version
